spring:
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  datasource:
    url: jdbc:postgresql://localhost:5432/activity
    username: activity
    password: activity
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate
  flyway:
    enabled: true
  mail:
    username: museums.guide1@gmail.com
    host: smtp.gmail.com
    port: 587
    password: Parola12345
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
rent:
  jwtSecret: mircea
  jwtExpirationMs: 864000000
